Add files via upload
gagc056/enumerable pull request #2
Opened 2019-11-04 09:05 UTC by lhscar56

2019-11-04 20:14 UTC, samgaco requested changes
Hi @lhscar56 :high_brightness: 

I left you some comments, please test your methods against the cases I attached and try to make changes accordingly so your methods give the expected results. 

Also, I would require from you to improve the readme file.

This project is a bit challenging, so good spirit :muscle: 

----------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +      yield check_self[i]
- [ ] my_each returns an Enumerator if no block is given

expected:

```
irb(main):167:0> [1,2].each
=> #<Enumerator: [1, 2]:each>
```

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +    i = 0
- [ ] my_each_with_index calls the given block once for each element in self

```
irb(main):177:0> [1,2,"b","c"].each_with_index {|n,e| puts n,e}
1
0
2
1
b
2
c
3
=> [1, 2, "b", "c"]
```

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +      my_each { |element| result &= (yield element) }
Please test your methods against the following, which you can find [here](https://ruby-doc.org/core-2.6.5/Enumerable.html)

```
%w[ant bear cat].all? { |word| word.length >= 3 } #=> true
%w[ant bear cat].all? { |word| word.length >= 4 } #=> false
%w[ant bear cat].all?(/t/)                        #=> false
[1, 2i, 3.14].all?(Numeric)                       #=> true
[nil, true, 99].all?                              #=> false
[].all?                                           #=> true
``` 

this is what is exactly failing with your method

- [ ] my_all? returns true if the block never returns false or nil
- [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +  end
test my_any? against:

 ```
%w[ant bear cat].any? { |word| word.length >= 3 } #=> true
%w[ant bear cat].any? { |word| word.length >= 4 } #=> true
%w[ant bear cat].any?(/d/)                        #=> false
[nil, true, 99].any?(Integer)                     #=> true
[nil, true, 99].any?                              #=> true
[].any?                                           #=> false
```

- [ ] my_any? returns true if the block ever returns a value other than false or nil
- [ ] my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +    end
```
%w{ant bear cat}.none? { |word| word.length == 5 } #=> true
%w{ant bear cat}.none? { |word| word.length >= 4 } #=> false
%w{ant bear cat}.none?(/d/)                        #=> true
[1, 3.14, 42].none?(Float)                         #=> false
[].none?                                           #=> true
[nil].none?                                        #=> true
[nil, false].none?                                 #=> true
[nil, false, true].none?                           #=> false
```

- [ ] my_none? returns true if the block never returns true for all elements
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +      my_each { |i| count += 1 if yield(i) == true }
```
ary = [1, 2, 4, 2]
ary.count               #=> 4
ary.count(2)            #=> 2
ary.count{ |x| x%2==0 } #=> 3
```

- [ ] my_count returns the number of items in enum through enumeration
- [ ] my_count counts the number of items in enum that are equal to item if an argument is given
- [ ] my_count counts the number of elements yielding a true value if a block is given

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +    arr = []
- [ ] my_map returns a new array with the results of running block once for every element in enum.

this should work:

 ```
irb(main):180:0> [1,2,3].map {|n| n*2}
=> [2, 4, 6]

```

2019-11-04 20:14 UTC, samgaco commented on enumerable.rb
> +    if block_given?
- [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

```
# Sum some numbers
(5..10).reduce(:+)                             #=> 45
# Same using a block and inject
(5..10).inject { |sum, n| sum + n }            #=> 45
# Multiply some numbers
(5..10).reduce(1, :*)                          #=> 151200
# Same using a block
(5..10).inject(1) { |product, n| product * n } #=> 151200
# find the longest word
longest = %w{ cat sheep bear }.inject do |memo, word|
   memo.length > word.length ? memo : word
end
longest                                        #=> "sheep"
```

2019-11-10 09:27 UTC, whiz25 approved these changes
## Awesome :clap:
You have made all the requested changes and your methods work as required. It's a :+1: from me.

### Martin Afani

2019-11-10 16:45 UTC, merged